export const MONTH = {
  JANUARY: 0,
  FEBRUARY: 1,
  MARCH: 2,
  APRIL: 3,
  MAY: 4,
  JUNE: 5,
  JULY: 6,
  AUGUST: 7,
  SEPTEMBER: 8,
  OCTOBER: 9,
  NOVEMBER: 10,
  DECEMBER: 11,
};

export const SEASON = {
  WINTER: 'winter',
  SPRING: 'spring',
  SUMMER: 'summer',
  AUTUMN: 'autumn',
};

export const YEAR = {
  WINTER_MONTHS: [MONTH.JANUARY, MONTH.FEBRUARY, MONTH.DECEMBER],
  SPRING_MONTHS: [MONTH.MARCH, MONTH.APRIL, MONTH.MAY],
  SUMMER_MONTHS: [MONTH.JUNE, MONTH.JULY, MONTH.AUGUST],
  AUTUMN_MONTHS: [MONTH.SEPTEMBER, MONTH.OCTOBER, MONTH.NOVEMBER],
};
